coverage:
  range: 50..100
  round: down
  precision: 2
  status:
    project:
      default:
        target: 75
        threshold: 2
    patch:
      default:
        target: 50
        threshold: 2
