dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - cd /tmp
  - GIT_SECRETS_RELEASE=1.3.0
  - wget https://github.com/awslabs/git-secrets/archive/${GIT_SECRETS_RELEASE}.tar.gz
  - tar -xvf ${GIT_SECRETS_RELEASE}.tar.gz
  - cd git-secrets-${GIT_SECRETS_RELEASE}/
  - sudo make install
  - cd ${TRAVIS_BUILD_DIR}
install:
  - pip install .
script: pre-commit run --all-files
after_success:
  - coverage run ./setup.py test > /dev/null
  - codecov --token=$CODECOV_TOKEN
